# .github/workflows/release.yml  — drop this into the eguwallet-desktop repo
#
# Triggers on any tag vX.Y.Z.
# Builds Windows x64 + macOS arm64 + macOS x64, then uploads binaries to
# /opt/eguwallet-downloads/ on egucluster3, which is bind-mounted into the
# eguwallet-web Docker container at dist/client/downloads/.
# Astro node server serves them at https://eguwallet.eu/downloads/.
#
# Required GitHub secrets (repo Settings → Secrets → Actions):
#
#   DOWNLOADS_SSH_KEY
#     Ed25519 private key for eguilde@egucluster3.eguilde.cloud
#     (stored in eguwallet-web/docs/ — ask team lead)
#
#   DOWNLOADS_SERVER_KNOWN_HOSTS
#     |1|ADCM0bIU3JJliPmgWaXvijrvejc=|IKOM5DeEFJorLSkpcLUft5RKjJQ= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAION58gHMicv7NHTeGF3dcv7IBWCq9x0OEa8yIIiixuxB

name: Release & Deploy

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DEPLOY_USER: eguilde
  DEPLOY_HOST: egucluster3.eguilde.cloud
  DEPLOY_PATH: /opt/eguwallet-downloads

jobs:

  build-windows:
    name: Build — Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: windows-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Stage artifact
        run: copy target\x86_64-pc-windows-msvc\release\eguwallet-desktop.exe eguwallet-desktop-windows-x64.exe
      - uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: eguwallet-desktop-windows-x64.exe
          retention-days: 1

  build-macos-arm64:
    name: Build — macOS arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-arm64-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --target aarch64-apple-darwin
      - name: Create DMG
        run: |
          mkdir dist-arm64
          cp target/aarch64-apple-darwin/release/eguwallet-desktop dist-arm64/
          hdiutil create -volname "EguWallet Desktop" \
            -srcfolder dist-arm64 -ov -format UDZO \
            eguwallet-desktop-macos-arm64.dmg
      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-binary
          path: eguwallet-desktop-macos-arm64.dmg
          retention-days: 1

  build-macos-x64:
    name: Build — macOS x64
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-x64-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --target x86_64-apple-darwin
      - name: Create DMG
        run: |
          mkdir dist-x64
          cp target/x86_64-apple-darwin/release/eguwallet-desktop dist-x64/
          hdiutil create -volname "EguWallet Desktop" \
            -srcfolder dist-x64 -ov -format UDZO \
            eguwallet-desktop-macos-x64.dmg
      - uses: actions/upload-artifact@v4
        with:
          name: macos-x64-binary
          path: eguwallet-desktop-macos-x64.dmg
          retention-days: 1

  deploy:
    name: Deploy to eguwallet.eu
    needs: [build-windows, build-macos-arm64, build-macos-x64]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOWNLOADS_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.DOWNLOADS_SERVER_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Upload to egucluster3
        run: |
          scp -i ~/.ssh/deploy_key \
            eguwallet-desktop-windows-x64.exe \
            eguwallet-desktop-macos-arm64.dmg \
            eguwallet-desktop-macos-x64.dmg \
            ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:${{ env.DEPLOY_PATH }}/

      - name: Cleanup
        if: always()
        run: rm -f ~/.ssh/deploy_key
